### ISSUE TITLE
открытие ссылки из другого приложения

### ISSUE THREAD

**Issue by Ilia1** [umerov1999/Fenrir-for-VK#2]
При открытии ссылки на группу в ВК из браузера выходит сообщение
`Build version: 1.15 
Current date: 2020-11-22 13:13:57 
Android: Android SDK: 23 (6.0.1) 
Device: Yota Devices Limited YD201 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke interface method 'void dev.ragnarok.fenrir.mvp.view.IFeedView.askToReload()' on a null object reference
	at dev.ragnarok.fenrir.mvp.presenter.FeedPresenter.onCachedFeedReceived(FeedPresenter.java:245)
	at dev.ragnarok.fenrir.mvp.presenter.FeedPresenter.lambda$loadCachedFeed$6$FeedPresenter(FeedPresenter.java:211)
	at dev.ragnarok.fenrir.mvp.presenter.-$$Lambda$FeedPresenter$vSQ7g8ZR_HarVYCL4lGcVveDkKE.accept(lambda)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5444)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:727)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
`

**Comment by umerov1999** [comment]
Это из-за другого бага, показ предложения обновить новости

**Comment by umerov1999** [comment]
исправлено
