### ISSUE TITLE
Fenrir 1.17, падение при попытке открыть удаленное фото по ссылке

### ISSUE THREAD

**Issue by platofff** [umerov1999/Fenrir-for-VK#3]
Открываю ссылку на удаленное фото: https://vk.com/dayvinchik?z=photo-91050183_458674436%2Falbum-91050183_00%2Frev и Fenrir падает.
```
Build version: 1.17 
Current date: 2020-12-07 11:28:46 
Android: Android SDK: 29 (10) 
Device: HMD Global Nokia 6.1 
 
Stack trace:  
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter subtitle
	at dev.ragnarok.fenrir.fragment.PhotoPagerFragment.setToolbarSubtitle(Unknown Source:2)
	at dev.ragnarok.fenrir.mvp.presenter.photo.PhotoPagerPresenter.resolveToolbarTitleSubtitleView(PhotoPagerPresenter.java:223)
	at dev.ragnarok.fenrir.mvp.presenter.photo.PhotoPagerPresenter.refreshInfoViews(PhotoPagerPresenter.java:288)
	at dev.ragnarok.fenrir.mvp.presenter.photo.PhotoPagerPresenter.onGuiCreated(PhotoPagerPresenter.java:154)
	at dev.ragnarok.fenrir.mvp.presenter.photo.PhotoPagerPresenter.onGuiCreated(PhotoPagerPresenter.java:55)
	at dev.ragnarok.fenrir.mvp.core.AbsPresenter.createView(AbsPresenter.kt:123)
	at dev.ragnarok.fenrir.mvp.compat.ViewHostDelegate.onViewCreated(ViewHostDelegate.kt:78)
	at dev.ragnarok.fenrir.mvp.compat.AbsMvpFragment.onViewCreated(AbsMvpFragment.kt:32)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7847)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by platofff** [comment]
Исправлено в 1.18
